---
# tasks file for roles/snap

- debug: var=ansible_facts.distribution_major_version

- debug: var=ansible_facts.distribution

- name: Enable epel repo 
  ansible.builtin.package:
    name: "{{ snap_epel9_repo }}"
    state: present 
  when: 
    - ansible_facts.distribution_major_version == 9    
    - ansible_facts.distribution == 'RedHat'
